const Discord = require("discord.js");
const client = new Discord.Client();
const client2 = new Discord.Client();
const client3 = new Discord.Client();
const client4 = new Discord.Client();
const client5 = new Discord.Client();
const client6 = new Discord.Client();
const client7 = new Discord.Client();
const client8 = new Discord.Client();
const client9 = new Discord.Client();
const client10 = new Discord.Client();
const client11 = new Discord.Client();
const client12 = new Discord.Client();
const client13 = new Discord.Client();
const client14 = new Discord.Client();
const client15 = new Discord.Client();
const client16 = new Discord.Client();
const client17 = new Discord.Client();
const client18 = new Discord.Client();
const client19 = new Discord.Client();
const client20 = new Discord.Client();
const client21 = new Discord.Client();
const client22 = new Discord.Client();
const client23 = new Discord.Client();
const client24 = new Discord.Client();
const client25 = new Discord.Client();
const client26 = new Discord.Client();
const client27 = new Discord.Client();
const client28 = new Discord.Client();
const client29 = new Discord.Client();
const client30 = new Discord.Client();
const client31 = new Discord.Client();
const client32 = new Discord.Client();
const client33 = new Discord.Client();
const client34 = new Discord.Client();
const client35 = new Discord.Client();
const client36 = new Discord.Client();
const client37 = new Discord.Client();
const client38 = new Discord.Client();
const client39 = new Discord.Client();
const client40 = new Discord.Client();
const client41 = new Discord.Client();
const client42 = new Discord.Client();
const client43 = new Discord.Client();
const client44 = new Discord.Client();
const client45 = new Discord.Client();
const client46 = new Discord.Client();
const client47 = new Discord.Client();
const client48 = new Discord.Client();
const client49 = new Discord.Client();
const client50 = new Discord.Client();

client.on('message', msg => {
  if (msg.content === '#dean') {
    msg.channel.send('Test Successful');
    msg.channel.sendFile('https://media.giphy.com/media/8GY3UiUjwKwhO/giphy.gif')
  }
});


client.login(process.env.BOT_TOKEN);
client2.login(process.env.BOT_TOKEN2);
client3.login(process.env.BOT_TOKEN3);
client4.login(process.env.BOT_TOKEN4);
client5.login(process.env.BOT_TOKEN5);
client6.login(process.env.BOT_TOKEN6);
client7.login(process.env.BOT_TOKEN7);
client8.login(process.env.BOT_TOKEN8);
client9.login(process.env.BOT_TOKEN9);
client10.login(process.env.BOT_TOKEN10);
client11.login(process.env.BOT_TOKEN11);
client12.login(process.env.BOT_TOKEN12);
client13.login(process.env.BOT_TOKEN13);
client14.login(process.env.BOT_TOKEN14);
client15.login(process.env.BOT_TOKEN15);
client16.login(process.env.BOT_TOKEN16);
client17.login(process.env.BOT_TOKEN17);
client18.login(process.env.BOT_TOKEN18);
client19.login(process.env.BOT_TOKEN19);
client20.login(process.env.BOT_TOKEN20);
client21.login(process.env.BOT_TOKEN21);
client22.login(process.env.BOT_TOKEN22);
client23.login(process.env.BOT_TOKEN23);
client24.login(process.env.BOT_TOKEN24);
client25.login(process.env.BOT_TOKEN25);
client26.login(process.env.BOT_TOKEN26);
client27.login(process.env.BOT_TOKEN27);
client28.login(process.env.BOT_TOKEN28);
client29.login(process.env.BOT_TOKEN29);
client30.login(process.env.BOT_TOKEN30);
client31.login(process.env.BOT_TOKEN31);
client32.login(process.env.BOT_TOKEN32);
client33.login(process.env.BOT_TOKEN33);
client34.login(process.env.BOT_TOKEN34);
client35.login(process.env.BOT_TOKEN35);
client36.login(process.env.BOT_TOKEN36);
client37.login(process.env.BOT_TOKEN37);
client38.login(process.env.BOT_TOKEN38);
client39.login(process.env.BOT_TOKEN39);
client40.login(process.env.BOT_TOKEN40);
client41.login(process.env.BOT_TOKEN41);
client42.login(process.env.BOT_TOKEN42);
client43.login(process.env.BOT_TOKEN43);
client44.login(process.env.BOT_TOKEN44);
client45.login(process.env.BOT_TOKEN45);
client46.login(process.env.BOT_TOKEN46);
client47.login(process.env.BOT_TOKEN47);
client48.login(process.env.BOT_TOKEN48);
client49.login(process.env.BOT_TOKEN49);
client50.login(process.env.BOT_TOKEN50);